---
title: "Open ideas, data and code sharing: epidemiologists should be in front!"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Emerson M. Del Ponte^1^, Adam H. Sparks^2^  
^1^Departamento de Fitopatologia, Universidade Federal de Viçosa, Viçosa MG 36570-000, Brazil;  ^2^Centre for Crop Health, University of Southern Queensland, Toowoomba, Qld 4350, Australia  
e-mail address: <delponte@ufv.br>

## Abstract

Botanical epidemiologists have long been leaders in using mathematical, statistical and computational approaches to tackle theoretical and applied research problems. Such skills always distinguished us from other plant pathology disciplines and naturally allowed us to bring together quantitative researchers (e.g. mathematicians, statisticians, programmers), which has been beneficial to our area of research. The availability of increasing amounts of data at scales from genomes to landscapes requires an even more diverse set of skills and enhanced ability to interact widely and advance the field. Additionally, donors, governments and journals are pushing for increased transparency and reproducibility (Bond-Lamberty et al. 2016). Because of this an open approach to science is quickly becoming more accepted, including unconstrained access and sharing of scientific content, data collection and computer code. It is envisioned that fostering open science attitudes within our research communities will lead to improved reproducibility of the research, both in relation to the methods and the findings. Adopting reproducible research practices directly benefits us as researchers. Between complicated analyses, reviews and revisions and questions years later about the data that was collected or analysis that was conducted, it’s extremely beneficial to be able to easily reproduce your work quickly and easily. Second, it is beneficial to the end-user or reader to be able to verify the validity of the methods used and recreate the analysis which helps with knowledge transfer. Lastly, sharing work openly and making it discoverable can lead to collaborations. While relatively few examples of reproducible research in plant pathology exist (Shah and Madden 2004), it is changing (Del Ponte 2018, Duku et al. 2015, Sparks et al. 2018). To help facilitate this change, we founded the Open Plant Pathology community (Del Ponte and Sparks 2018), which aims to foster relationships between researchers and promote open, transparent and reproducible research using shared data and reusable software. With our history of moving plant pathology forward using computational resources, botanical epidemiologists should be in front leading the way for plant pathology with these new methods.

## References 

Bond-Lamberty, B., Smith, A.P., & Bailey, V. 2016: Running an open experiment: transparency and reproducibility in soil and ecosystem science. Environ. Res. Lett., 11:084004.  
Del Ponte, E.M.: Reproducible report: Meta-analysis of relationships between white mold and soybean yield. [WWW document] URL https://emdelponte.github.io/paper-white-mold-meta-analysis. Cited 22 May. 2018.  
Del Ponte E.M. & Sparks A.H.: Open Plant Pathology: a Community to Promote Open Science Practices Including Data, Code and Research Outcomes in Plant Pathology. [WWW document] URL https://www.openplantpathology.org/. Cited 22 May. 2018.  
Duku, C., Sparks, A.H. & Zwart, S.J. 2016: Spatial modelling of rice yield losses in Tanzania due to bacterial leaf blight and leaf blast in a changing climate. Clim. Change., 135:569-583.  
Shah, D.A., and Madden, L.V. 2004: Nonparametric analysis of ordinal data in designed factorial experiments. Phytopathology., 94:33-43.  
Sparks, A.H., Del Ponte, E.M., Everhart, S., Foster, Z.S.L., Grünwald, N., (2018). Compendium of R code and data for ‘Status and Best Practices for Reproducible Research In Plant Pathology’. DOI: 10.5281/zenodo.1250665. Cited 22 May. 2018.
